[project]
name = "nyc-restaurant-inspection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "commitizen>=4.13.7",
    "pandas>=3.0.0",
]
